
local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3')))()

local w = library:CreateWindow("Stick Guns GUI") -- Creates the window

local b = w:CreateFolder("Item Giver Panel") -- Creates the folder(U will put here your buttons,etc)
local e = w:CreateFolder("Fun Stuff") -- Creates the folder(U will put here your buttons,etc)


b:Button("Stick",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("Stick")
end)
b:Button("BigStick",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("BigStick")
end)
b:Button("Pistol",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("StickPistol")
end)
b:Button("Sniper",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("StickSniper")
end)
b:Button("HeavySniper",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("StickHeavySniper")
end)
b:Button("SMG",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("StickSMG")
end)
b:Button("MicroSMG",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("StickMicroSMG")
end)
b:Button("Dual Pistols",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("DualStickPistol")
end)
b:Button("Rifle",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("StickRifle")
end)
b:Button("Dual MicroSMG",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("DualStickMicroSMG")
end)
b:Button("Rock Launcher",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("RockLauncher")
end)
b:Button("Shotgun",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("StickShotgun")
end)
b:Button("Boom Stick",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("Boomstick")
end)
b:Button("Pine Grenade",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("PineGrenade")
end)
b:Button("Pine Bomb",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("PineBomb")
end)
b:Button("Holy Hand Grenade",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("HolyHandGrenade")
end)
b:Button("Binoculars",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("Binoculars")
end)
b:Button("Stick Of Truth",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("StickOfTruth")
end)
b:Button("Radar",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("Radar")
end)
b:Button("Teleporter",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("Teleporter")
end)
b:Button("Quick Heal",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("QuickHeal")
end)
b:Button("Mortar",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("Mortar")
end)
b:Button("Whoopie Cushion",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("WhoopieCushion")
end)
b:Button("Menu Prop Pistol",function()
 game:GetService("ReplicatedStorage").RemoteEvents.RequestWeapon:FireServer("MenuPistolProp")

end)
e:Button("Winner Winner Badge",function()
game:GetService("ReplicatedStorage").RemoteEvents.GiveWinnerWinnerBadge:FireServer()

end)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
e:Button("Local Kill Message",function()
local ohString1 = "Stick Guns GUI"

game:GetService("ReplicatedStorage").RemoteEvents.Kill:Fire(ohString1)
end)
e:Button("Grenade On Self",function()
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohVector31 = Vector3.new(0,0,0)
local ohString2 = "PineGrenade"
local ohNumber3 = 3

game:GetService("ReplicatedStorage").RemoteEvents.SpawnProjectile:FireServer(ohVector31, ohString2, ohNumber3)
end)
e:Button("Holy Grenade On Self",function()
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohVector31 = Vector3.new(0,0,0)
local ohString2 = "HolyHandGrenade"
local ohNumber3 = 3

game:GetService("ReplicatedStorage").RemoteEvents.SpawnProjectile:FireServer(ohVector31, ohString2, ohNumber3)
end)
e:Button("Bomb On Self",function()
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohVector31 = Vector3.new(0,0,0)
local ohString2 = "PineBomb"
local ohNumber3 = 3

game:GetService("ReplicatedStorage").RemoteEvents.SpawnProjectile:FireServer(ohVector31, ohString2, ohNumber3)
end)

--[[
How to refresh a dropdown:
1)Create the dropdown and save it in a variable
local yourvariable = b:Dropdown("Hi",yourtable,function(a)
    print(a)
end)
2)Refresh it using the function
yourvariable:Refresh(yourtable)
How to refresh a label:
1)Create your label and save it in a variable
local yourvariable = b:Label("Pretty Useless NGL",{
    TextSize = 25; -- Self Explaining
    TextColor = Color3.fromRGB(255,255,255);
    BgColor = Color3.fromRGB(69,69,69);
})
2)Refresh it using the function
yourvariable:Refresh("Hello") It will only change the text ofc
]]